### ISSUE TITLE
provider on terraform registry

### ISSUE THREAD

**Issue by marshall7m** [apparentlymart/terraform-provider-bash#1]
Hi there,

Just wondering if and when this provider will be on the terraform registry.

Thanks

**Comment by apparentlymart** [comment]
Hi @marshall7m,

I did already attempt to publish this but had some issues with my gpg key that I've not yet had time to investigate. With this being a spare time project, I'm not sure when I'll have more time to spend on it.

**Comment by apparentlymart** [comment]
Hi again,

The new possibility of this provider exporting a function rather than a data source gave me incentive to revisit it, since the functionality here is better suited to a function anyway.

Therefore I've now posted a release of this provider in Terraform registry, but this new release won't be useful until you are using Terraform v1.8.0 or later because provider-contributed functions are not accessible from earlier Terraform versions.
