### ISSUE TITLE
How to use this provider

### ISSUE THREAD

**Issue by Parth909** [apparentlymart/terraform-provider-bash#2]
When i use the provider like this 
```tf

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
    bash = {
      source = "apparentlymart/bash"
    }
  }
```
It gives the following error 👇 which is understandable bcz it is not available on official terraform registry
![image](https://user-images.githubusercontent.com/59220026/179236602-6330838c-b6c0-4ae3-bdaa-9d69f73ec2cc.png)

When used like this 👇 it is also understandable as using the github repo url instead of terraform registry.
![image](https://user-images.githubusercontent.com/59220026/179237301-7ca17fdc-0a9d-467a-a98d-cfba1fbeab8c.png)

Do i need to download the released binary & use it. If so then how to do it

**Comment by apparentlymart** [comment]
Hi @Parth909,

Unfortunately due to unresolved problems with my GPG key I have not been able to publish this provider in the public registry yet. Therefore it's not available for automatic installation from anywhere, and so you'd need to install it manually on your local system.

One way to achieve that would be to download one of [the v0.1.0 release packages](https://github.com/apparentlymart/terraform-provider-bash/releases/tag/v0.1.0) (whichever one whose platform matches the platform that Terraform reports when you run `terraform version`) and extract it into one of Terraform's [Implied Local Mirror Directories](https://www.terraform.io/cli/config/config-file#implied-local-mirror-directories).

For example, if you were running Terraform on `linux_amd64` then you could:
* Download `terraform-provider-bash_0.1.0_linux_amd64.zip`
* Create a directory `$HOME/.local/share/terraform/plugins/registry.terraform.io/apparentlymart/bash/0.1.0/linux_amd64`
* Extract the contents of the zip file into that new directory, so that the plugin executable ends up at `$HOME/.local/share/terraform/plugins/registry.terraform.io/apparentlymart/bash/0.1.0/linux_amd64/terraform-provider-bash`

(I used a `registry.terraform.io/apparentlymart/...` address for the above, even though this isn't currently published there, because I _have_ already claimed that name in the registry and hope to publish this provider there someday, so using that namespace now would hopefully allow seamlessly migrating to automatic installation once I figure that out.

I know this is very inconvenient and so I'd understand considering this provider effectively unusuable for the moment. Unfortunately the Terraform Registry doesn't really give good feedback about signature errors during publishing and so I've not yet been able to figure out what is wrong with my signatures, given that I've been able to use the same technique to publish [other providers](https://registry.terraform.io/namespaces/apparentlymart) before. Hopefully I'll have some more time to investigate this someday, but I'm busy with other things right now. :confounded:

**Comment by coogle** [comment]
I don't suppose there is any update here on trying to get this provider into the registry? The ability to generate a bash script for a launch template and include some outputs (e.g. the RDS endpoint) is exactly what I'm looking for and this seems like what I need... but I can't use it if I have to do special hackery!

**Comment by apparentlymart** [comment]
Hi @coogle,

Unfortunately this provider is very far from the top of my priority list and so I don't anticipate being able to spend any more time on it for the foreseeable future.

If you or someone else has a strong need for it then I think probably the best idea for right now would be to fork this repository into your own GitHub account (either personal or organizational) and then publish it into the public registry yourself under your own namespace. This code is under a liberal open source license, and even if it were not I do not intend to try to sue anyone for using what is a relatively small piece of code.

Hopefully you won't have the same strange GPG key problems I have with Terraform Registry, although since I've not yet debugged why it wasn't working I can't be sure.

**Comment by apparentlymart** [comment]
Hi all,

The new possibility of this provider exporting a function rather than a data source gave me incentive to revisit it, since the functionality here is better suited to a function anyway.

Therefore I've now posted a release of this provider in Terraform registry, but this new release won't be useful until you are using Terraform v1.8.0 or later because provider-contributed functions are not accessible from earlier Terraform versions.
